apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:dIWEwRPbx2Yiutr4AyVwSiHfz42wUwBavtNJwgwjowlXbCUj+9koSw==,iv:X9I25IbDzTN6MeR4O7yPizLwRtsQK9hSYNcepUudrxk=,tag:Ae8gFQhP/dl0SByj+fmw4w==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQzVNWEVRTTM1OFhnZzMv
        MFVPNUNpV3BlNFc2NXRoL1hRRzIvYVdLUWhRCnFOT3A0cGtjekJwZURwWG0zdURy
        Y2hVY1VFcTZpQStzelNVWVF3M0xEUGMKLS0tIFN2YldhY0hGdlBJb1R1UXp2blRy
        bG5EOFhML2VScGkwVlY3alpJY1oyL1kKB0c8QBNT14iP1AEfektDO7ZY0iHhQnOi
        AsYRaxv9JoR+k+ADJy94DLLij8zM6ac12vqMgyyQDAEjTbsXWNCU2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T16:02:32Z"
  mac: ENC[AES256_GCM,data:rhiGZbuAterph5WzIFNg4kWLi4rau45+jBsMxIvdPBeGVVR1vKNn7imJoHEw6x1ropwExCSIFqYI1c73hwkTT67IadtRlrsiXxxw3p7DLXDVxsmZjKDA+JUenn0XyuD6ItJAx5UA6cgAwkUWLX2ieX1o60At4n+hRbDmJAYoyBM=,iv:ZU1kms6vGuvy2NLwI36R9bgxSSiaIpCX0N282wuGQuo=,tag:iiP8uV4CV1So0NyL199RqA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
