apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:TTq56YNQ27hy3dPaj9oVV6DxxtM/hVbjQh0y39ryVFnsFxMdKACoSg==,iv:TY9knIP7YG3FAxIYTzmnVe6GfT4zdOCJKX+leqIrc0g=,tag:6Fy0kiC1klgOSHwlyVx4jA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQzVNWEVRTTM1OFhnZzMv
        MFVPNUNpV3BlNFc2NXRoL1hRRzIvYVdLUWhRCnFOT3A0cGtjekJwZURwWG0zdURy
        Y2hVY1VFcTZpQStzelNVWVF3M0xEUGMKLS0tIFN2YldhY0hGdlBJb1R1UXp2blRy
        bG5EOFhML2VScGkwVlY3alpJY1oyL1kKB0c8QBNT14iP1AEfektDO7ZY0iHhQnOi
        AsYRaxv9JoR+k+ADJy94DLLij8zM6ac12vqMgyyQDAEjTbsXWNCU2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T21:21:13Z"
  mac: ENC[AES256_GCM,data:frGKZrkZjO+inq8nlxWiKhNAAPBmZTXNh1dkNQVviViObmzaeHWcEOdaigKgFSMQ/gqfvjPNxxU6YH1zOXjLqdPKGv7UkcBqvcSfpky9L7Vh01nxmasVUtlZiM45Rez6gb9SPLMUrxesFfRa5+LgsTsRsK5Ah0sSkgUFNe7BKzs=,iv:fEXsguSCCL+GjJiLAwQmfBnugBZFS4i3gXk52natmio=,tag:liZLdrc6f4zHjqvhr0M5vA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
