apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:TTq56YNQ27hy3dPaj9oVV6DxxtM/hVbjQh0y39ryVFnsFxMdKACoSg==,iv:TY9knIP7YG3FAxIYTzmnVe6GfT4zdOCJKX+leqIrc0g=,tag:6Fy0kiC1klgOSHwlyVx4jA==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQzVNWEVRTTM1OFhnZzMv
        MFVPNUNpV3BlNFc2NXRoL1hRRzIvYVdLUWhRCnFOT3A0cGtjekJwZURwWG0zdURy
        Y2hVY1VFcTZpQStzelNVWVF3M0xEUGMKLS0tIFN2YldhY0hGdlBJb1R1UXp2blRy
        bG5EOFhML2VScGkwVlY3alpJY1oyL1kKB0c8QBNT14iP1AEfektDO7ZY0iHhQnOi
        AsYRaxv9JoR+k+ADJy94DLLij8zM6ac12vqMgyyQDAEjTbsXWNCU2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T20:05:50Z"
  mac: ENC[AES256_GCM,data:rSzYmFSGi5gv/VE6z8ejvR4ziAr6PFlstqW9BtxfjFQO4B3s2QOeYF201rxDEMjC1nPBWRuNfSQ4XhA55kc0pgtVMQhiHcLEBiz+g96uN6me21eR7Q9u81VnACeI7BaD+t+zoqtQwia7wtFJlpiuIZKTuqFsA4e3nx3V9SuY/Lo=,iv:NAdAO5++zBrnvOfq1JRaChG8JpbPNdtHMz23SY8rnmk=,tag:MnNuC5jA9bj2AHaDsAqCCA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
