apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:9jFVhiQ+YlrrtN/P0s9J7Hhx7zI7NCQec2AS+fKRxbdl8Qedfg==,iv:0+QAxe+VJzwmzTkN0xshFwGeLTsnrvOmohU/bDZyDiM=,tag:coqhWeJXBOE51vrqfC01UQ==,type:str]
sops:
  age:
    - recipient: age13swsp40tstrqluer6arm5skldvg5ucw4t390a87qcdzcj0r2jscqrraxnv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaQzVNWEVRTTM1OFhnZzMv
        MFVPNUNpV3BlNFc2NXRoL1hRRzIvYVdLUWhRCnFOT3A0cGtjekJwZURwWG0zdURy
        Y2hVY1VFcTZpQStzelNVWVF3M0xEUGMKLS0tIFN2YldhY0hGdlBJb1R1UXp2blRy
        bG5EOFhML2VScGkwVlY3alpJY1oyL1kKB0c8QBNT14iP1AEfektDO7ZY0iHhQnOi
        AsYRaxv9JoR+k+ADJy94DLLij8zM6ac12vqMgyyQDAEjTbsXWNCU2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T19:54:55Z"
  mac: ENC[AES256_GCM,data:1jCbddluDCOEVJRoG1h2XdlD21/+bHN1OLDHpvKD+KH6Bs+sVYV2H+6V++StjRqqbRnDc6JPCmS0cFJLr1tgC5tvAEQmMobU/iIy+XWGZagJtBCsBDq/tr1JqbTpXo/MYyBOAWcwQrgAm7XlOPHmhoTuHyeRx9X4wpuO3Lj/tlw=,iv:PF8NmPtBtB3jEZyuS91AYEfVBNF5C0zise9DqYdwS24=,tag:GP8mLbk7IipPvTFpl0iQ5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
