apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app gitlab-runner
  namespace: gitlab-runner
spec:
  interval: 30m
  chart:
    spec:
      chart: gitlab-runner 
      version: "0.84.1"
      sourceRef:
        kind: HelmRepository
        name: gitlab
        namespace: gitlab-runner
      interval: 12h
  values:
    gitlabUrl: "https://gitlab.com/"
    runnerRegistration: "${GITLAB_RUNNER_REGISTRATION_TOKEN}"
