---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app altcha-avto-masini
  namespace: avto-masini
spec:
  interval: 30m
  chart:
    spec:
      chart: altcha-sentinel
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: altcha-org
        namespace: avto-masini
  # install:
  #   crds: CreateReplace
  #   remediation:
  #     retries: 3
  # upgrade:
  #   cleanupOnFail: true
  #   crds: CreateReplace
  #   remediation:
  #     strategy: rollback
  #     retries: 3
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      className: avto-masini
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "altcha.${SECRET_PROD_DOMAIN}"
      hosts:
        - host: altcha.${SECRET_PROD_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
