---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app altcha-sentinel
  namespace: avto-masini
spec:
  interval: 30m
  chart:
    spec:
      chart: sentinel
      sourceRef:
        kind: HelmRepository
        name: altcha-org
        namespace: flux-system

    ingress:
      enabled: true
      className: avto-masini
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "altcha.${SECRET_PROD_DOMAIN}"
      hosts:
        - host: altcha.${SECRET_PROD_DOMAIN}
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: "${SECRET_PROD_DOMAIN/./-}-production-tls"
          hosts:
            - altcha.${SECRET_PROD_DOMAIN}
