---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: avto-masini-web-production-ingress
  namespace: avto-masini
  annotations:
    external-dns.alpha.kubernetes.io/target: "${SECRET_PROD_DOMAIN}"
    external-dns.alpha.kubernetes.io/hostname: "${SECRET_PROD_DOMAIN}, www.${SECRET_PROD_DOMAIN}"
spec:
  ingressClassName: avto-masini
  rules:
    - host: "${SECRET_PROD_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avto-masini-web-production
                port:
                  name: prod-svc
    - host: "www.${SECRET_PROD_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: avto-masini-web-production
                port:
                  name: prod-svc
