apiVersion: apps/v1
kind: Deployment
metadata:
  name: bentopdf
  namespace: bentopdf
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: bentopdf
  strategy:
    # Restrict to a Single bentopdf instance, on redeploys it will tear down the old one before bring a new one up.
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: bentopdf
    spec:
      containers:
        - name: bentopdf
          image: bentopdf/bentopdf-simple:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          # Use the http server for pod health checks
          livenessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: bentopdf
  namespace: bentopdf
spec:
  selector:
    app.kubernetes.io/name: bentopdf
  ports:
    - port: 8080
      name: http
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bentopdf-ingress
  namespace: bentopdf
  annotations:
    external-dns.alpha.kubernetes.io/target: "ilovepdf.${SECRET_EXTERNAL_DOMAIN}"
spec:
  ingressClassName: external
  rules:
    - host: ilovepdf.${SECRET_EXTERNAL_DOMAIN}
      http:
        paths:
          - backend:
              service:
                name: bentopdf
                port: 
                  name: http
            path: /
            pathType: Prefix
