apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-database
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filebrowser-config
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobooks-filebrowser
  namespace: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobooks-filebrowser
  template:
    metadata:
      labels:
        app: audiobooks-filebrowser
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      containers:
      - name: filebrowser
        image: filebrowser/filebrowser
        args:
          - --baseurl=/filebrowser
        ports:
        - containerPort: 80
        volumeMounts:
        - name: audiobooks
          mountPath: /srv
        - name: database
          mountPath: /database
        - name: config
          mountPath: /config
      volumes:
      - name: audiobooks
        persistentVolumeClaim:
          claimName: audiobooks
      - name: database
        persistentVolumeClaim:
          claimName: filebrowser-database
      - name: config
        persistentVolumeClaim:
          claimName: filebrowser-config
---
apiVersion: v1
kind: Service
metadata:
  name: audiobooks-filebrowser
  namespace: audiobookshelf
spec:
  selector:
    app: audiobooks-filebrowser
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: audiobooks-filebrowser-ingress
  namespace: audiobookshelf
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: external
  rules:
    - host: "books.cloudwithdan.com"
      http:
        paths:
          - path: /filebrowser(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: audiobooks-filebrowser
                port:
                  number: 80
