---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  interval: 30m
  chart:
    spec:
      chart: audiobookshelf
      version: 0.0.2-nightly.49
      sourceRef:
        kind: HelmRepository
        name: audiobookshelf
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    persistence:
      config:
        enabled: true
        size: 1Gi
        storageClass: "longhorn"
      metadata:
        enabled: true
        size: 10Gi
        storageClass: "longhorn"

    persistentVolumeClaims:
      - name: audiobooks
        mountPath: /audiobooks
        readOnly: false

    volumes:
      - name: audiobooks
        persistentVolumeClaim:
          claimName: audiobooks-pvc

    volumeMounts:
      - name: audiobooks
        mountPath: "/audiobooks"
        readOnly: false 

    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/target: books.${SECRET_EXTERNAL_DOMAIN}
        nginx.ingress.kubernetes.io/auth-url: |-
          http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        nginx.ingress.kubernetes.io/auth-signin: |-
          https://auth.${SECRET_EXTERNAL_DOMAIN}/outpost.goauthentik.io/start?rd=$scheme%3A%2F%2F$host$escaped_request_uri
        nginx.ingress.kubernetes.io/auth-response-headers: |-
          Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        nginx.ingress.kubernetes.io/auth-snippet: |
          proxy_set_header X-Forwarded-Host $http_host;
        kubernetes.io/ingress.class: external
      hosts:
        - host: books.${SECRET_EXTERNAL_DOMAIN}
          paths:
            - path: /
              pathType: Prefix
